---
server:
  port: 8088
  shutdown: "graceful"
spring:
  application:
    name: "media"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${KEYCLOAK_ISSUER_URI}"
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:${APP_POSTGRES_PORT:5432}/${APP_DB_NAME:media}"
    username: "${POSTGRES_ADMIN_USER:zlink}"
    password: "${POSTGRES_ADMIN_PASSWORD}"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: "validate"
    show-sql: false
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: "varchar"
  liquibase:
    change-log: "classpath:cm/klg/media/repository/liquibase/changelog/master.xml"
    enabled: true
jk-dev:
  events-messaging:
    inbox:
      enabled: "${DOMAIN_EVENTS_MESSAGING_CONSUMER_ENABLED:false}"
      batchSize: "${SCHEDULER_EVENT_NOTIFICATION_BATCH_SIZE:1000}"
      frequency: "${SCHEDULER_EVENT_NOTIFICATION_FREQUENCY:5000}"
    outbox:
      enabled: "${DOMAIN_EVENTS_MESSAGING_PUBLISHER_ENABLED:false}"
      batchSize: "${SCHEDULER_EVENT_NOTIFICATION_BATCH_SIZE:1000}"
      frequency: "${SCHEDULER_EVENT_NOTIFICATION_FREQUENCY:5000}"
  storage:
    max-document-size-in-bytes: "${STORAGE_MAX_DOCUMENT_SIZE_IN_BYTES:5242880}"
    s3:
      url: "${STORAGE_S3_URI:http://localhost:9000}"
      credentials:
        name: "${STORAGE_S3_ACCESS_NAME}"
        secret: "${STORAGE_S3_ACCESS_SECRET}"
      bucket-name: "${STORAGE_S3_BUCKET_NAME:zlink}"
logging:
  level:
    root: "INFO"
    cm.klg.service_provider: "DEBUG"
    org.springframework.web: "INFO"
    org.springframework.security: "INFO"
    org.hibernate: "INFO"
    org.springframework.boot.autoconfigure.liquibase: "DEBUG"
    liquibase: "INFO"
    org.hibernate.tool.schema: "DEBUG"
